name: Build GKI custom

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      use_make:
        description: 'Build with MAKE?'
        required: true
        type: boolean
        default: true
      kernel_variant:
        description: 'Choose Kernel Variant'
        required: true
        type: choice
        options:
          - WILD
          - KSU
          - NEXT
        default: NEXT
      kernel_uname:
        description: 'Set kernel uname (exmaple: name after 6.1.90 or leave blank for no name)'
        required: true
        type: string
        default: ""
      kernelsu_branch:
        description: 'Choose ksu branch'
        required: true
        type: choice
        options:
          - Stable
          - Dev
          - Other
        default: Dev
      kernelsu_branch_other:
        description: "If 'Other' is selected, specify your custom branch"
        required: false
        type: string
        default: ""
jobs:
  build-kernels-a12-5-10:
    name: ${{ inputs.kernel_variant }}-Android_12-5.10
    uses: ./.github/workflows/kernel-a12-5-10.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernel_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
      use_make: ${{ inputs.use_make }}
  build-kernels-a13-5-10:
    name: ${{ inputs.kernel_variant }}-Android_13-5.10
    uses: ./.github/workflows/kernel-a13-5-10.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernel_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
      use_make: ${{ inputs.use_make }}
  build-kernels-a13-5-15:
    name: ${{ inputs.kernel_variant }}-Android_13-5.15
    uses: ./.github/workflows/kernel-a13-5-15.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernel_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
      use_make: ${{ inputs.use_make }}
  build-kernels-a14-5-15:
    name: ${{ inputs.kernel_variant }}-Android_14-5.15
    uses: ./.github/workflows/kernel-a14-5-15.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernel_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
      use_make: ${{ inputs.use_make }}
  build-kernels-a14-6-1:
    name: ${{ inputs.kernel_variant }}-Android_14-6.1
    uses: ./.github/workflows/kernel-a14-6-1.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernel_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
      use_make: ${{ inputs.use_make }}
  build-kernels-a15-6-6:
    name: ${{ inputs.kernel_variant }}-Android_15-6.6
    uses: ./.github/workflows/kernel-a15-6-6.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernel_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
      use_make: ${{ inputs.use_make }}